.lavapipe-test:
  stage: software-renderer
  extends:
    - .test-vk
    - .lavapipe-rules
    - .deqp-test-vk
  variables:
    GPU_VERSION: lvp
    VK_DRIVER: lvp
    DEQP_EXPECTED_RENDERER: llvmpipe

lavapipe-vk:
  stage: software-renderer
  extends:
    - .lavapipe-test
  variables:
    DEQP_FRACTION: 10

lavapipe-nir-stress:
  extends:
    - .lavapipe-test
  variables:
    DEQP_FRACTION: 100
    NIR_DEBUG: "clone,serialize"

lavapipe-vk-asan:
  extends:
    - .lavapipe-test
  variables:
    GPU_VERSION: lvp-asan
    DEQP_FRACTION: 1000
    # Skip dlclose so that we get good backtraces of the leaks.
    # Don't batch the tests into caselists while we're leaky.
    DEQP_RUNNER_OPTIONS: "--env LD_PRELOAD=libasan.so.6:libdlclose-skip.so --tests-per-group 1"
  needs:
    - debian/x86_test-vk
    - debian-testing-asan
